version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
      
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: webui/Dockerfile
    depends_on:
      - backend
    ports:
      - "8501:8501"
